removed the cancel-workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,39 +28,39 @@ jobs:
         with:
           name: my-artifact
 
-  timeout:
-    runs-on: ubuntu-latest
+  # timeout:
+    # runs-on: ubuntu-latest
 
-    steps:
-      - name: Set start time
-        id: set_start_time
-        run: echo "##[set-output name=start_time]$(date +%s)"
+    # steps:
+    #   - name: Set start time
+    #     id: set_start_time
+    #     run: echo "##[set-output name=start_time]$(date +%s)"
 
-      - name: Wait for 30 seconds
-        run: sleep 30s
+    #   - name: Wait for 30 seconds
+    #     run: sleep 30s
 
-      - name: Check approval status
-        # uses: styfle/cancel-workflow-action@0.9.1
-        # with:
-        #   workflow_id: ${{ github.workflow_id }}
-        # if: ${{ failure() }}  # Execute only if the previous step failed (timeout)
-        run: |
-          echo "Approval job status check after timeout"
-          echo "Initiating cancellation of the workflow run..."
+    #   - name: Check approval status
+    #     # uses: styfle/cancel-workflow-action@0.9.1
+    #     # with:
+    #     #   workflow_id: ${{ github.workflow_id }}
+    #     # if: ${{ failure() }}  # Execute only if the previous step failed (timeout)
+    #     run: |
+    #       echo "Approval job status check after timeout"
+    #       echo "Initiating cancellation of the workflow run..."
 
-          export RUN_ID=${{ github.run_id }}
-          # echo "$RUN_ID"
-          echo "RUN_ID: $RUN_ID"
-          echo "END OF run id"
-          export TOKEN=${{ github.token }} 
-          echo "$TOKEN"
-          echo "END OF LINE"
-          curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github.v3+json" \
-            -H "Authorization: Bearer $TOKEN" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/mayankmj/repo-2/actions/runs/$RUN_ID/cancel"
+    #       export RUN_ID=${{ github.run_id }}
+    #       # echo "$RUN_ID"
+    #       echo "RUN_ID: $RUN_ID"
+    #       echo "END OF run id"
+    #       export TOKEN=${{ github.token }} 
+    #       echo "$TOKEN"
+    #       echo "END OF LINE"
+    #       curl -L \
+    #         -X POST \
+    #         -H "Accept: application/vnd.github.v3+json" \
+    #         -H "Authorization: Bearer $TOKEN" \
+    #         -H "X-GitHub-Api-Version: 2022-11-28" \
+    #         "https://api.github.com/repos/mayankmj/repo-2/actions/runs/$RUN_ID/cancel"
 
-          exit 1  # Exit with an error code to force cancel the workflow
+    #       exit 1  # Exit with an error code to force cancel the workflow
         
